/**
 * Compiles the Tailwind CSS used by the invoice PDF templates into a plain
 * string module that the PDF service can inject directly.
 *
 * Previously every PDF request did `page.addStyleTag({ url: TAILWIND_CDN })`,
 * a serial network round trip to a CDN pinned at Tailwind v2.2.19 — two majors
 * behind the app's own 3.3.5, which is why generated PDFs could drift visually
 * from the live preview. Compiling here removes the request entirely and puts
 * the PDF on the same Tailwind version as the rest of the app.
 *
 * It also embeds the fonts as base64 @font-face rules. Previously the
 * templates linked Google Fonts, which meant the PDF depended on a third party
 * at request time — and worse, the wait for it was unreliable:
 * `document.fonts.ready` resolves immediately when the stylesheet has not been
 * fetched yet (nothing is pending), so Chromium printed with a fallback font.
 * Embedding removes both the network dependency and the race.
 *
 * Fonts are read from node_modules (@fontsource/*) rather than downloaded, so
 * builds stay reproducible and work offline.
 *
 * Runs from the `prebuild` / `predev` npm scripts.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import postcss from "postcss";
import tailwindcss from "tailwindcss";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const outFile = resolve(projectRoot, "lib/pdfStyles.generated.ts");

/**
 * Only the weights the templates actually use, latin subset only. Each extra
 * weight is ~15-20kB of base64 in the generated module.
 */
const FONT_FACES = [
    { family: "Outfit", pkg: "outfit", weights: [400, 500, 600, 700] },
    { family: "Dancing Script", pkg: "dancing-script", weights: [400] },
    { family: "Parisienne", pkg: "parisienne", weights: [400] },
    { family: "Great Vibes", pkg: "great-vibes", weights: [400] },
    { family: "Alex Brush", pkg: "alex-brush", weights: [400] },
];

async function buildFontFaces() {
    const rules = [];

    for (const { family, pkg, weights } of FONT_FACES) {
        for (const weight of weights) {
            const file = resolve(
                projectRoot,
                `node_modules/@fontsource/${pkg}/files/${pkg}-latin-${weight}-normal.woff2`
            );

            const base64 = (await readFile(file)).toString("base64");

            rules.push(
                `@font-face{font-family:'${family}';font-style:normal;` +
                    `font-weight:${weight};font-display:block;` +
                    `src:url(data:font/woff2;base64,${base64}) format('woff2');}`
            );
        }
    }

    return rules.join("");   // CSS needs no separator between rules
}

const templateGlob = resolve(
    projectRoot,
    "app/components/templates/invoice-pdf/**/*.tsx"
).replace(/\\/g, "/");

async function main() {
    const result = await postcss([
        tailwindcss({
            content: [templateGlob],
            // The PDF is standalone HTML rendered by Chromium — it does not
            // inherit the app's theme tokens or dark mode.
            darkMode: "media",
            theme: {},
            plugins: [],
        }),
    ]).process("@tailwind base;\n@tailwind utilities;\n", {
        from: undefined,
    });

    const fontCss = await buildFontFaces();
    const css = fontCss + result.css;

    const banner = [
        "// AUTO-GENERATED by scripts/build-pdf-css.mjs — do not edit by hand.",
        "// Regenerate with `npm run build:pdf-css`.",
        "",
        "export const PDF_TAILWIND_CSS = String.raw`",
    ].join("\n");

    // String.raw still terminates on a backtick and interpolates on ${.
    const escaped = css.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, `${banner}${escaped}\`;\n`, "utf8");

    const kb = (Buffer.byteLength(css, "utf8") / 1024).toFixed(1);
    const fontKb = (Buffer.byteLength(fontCss, "utf8") / 1024).toFixed(1);
    console.log(
        `[pdf-css] wrote ${outFile} (${kb} kB total, ${fontKb} kB embedded fonts)`
    );
}

main().catch((error) => {
    console.error("[pdf-css] failed to build PDF stylesheet:", error);
    process.exit(1);
});
