/**
 * Compiles the Tailwind CSS used by the invoice PDF templates into a plain
 * string module that the PDF service can inject directly.
 *
 * Previously every PDF request did `page.addStyleTag({ url: TAILWIND_CDN })`,
 * a serial network round trip to a CDN pinned at Tailwind v2.2.19 — two majors
 * behind the app's own 3.3.5, which is why generated PDFs could drift visually
 * from the live preview. Compiling here removes the request entirely and puts
 * the PDF on the same Tailwind version as the rest of the app.
 *
 * Runs from the `prebuild` / `predev` npm scripts.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import postcss from "postcss";
import tailwindcss from "tailwindcss";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");
const outFile = resolve(projectRoot, "lib/pdfStyles.generated.ts");

const templateGlob = resolve(
    projectRoot,
    "app/components/templates/invoice-pdf/**/*.tsx"
).replace(/\\/g, "/");

async function main() {
    const result = await postcss([
        tailwindcss({
            content: [templateGlob],
            // The PDF is standalone HTML rendered by Chromium — it does not
            // inherit the app's theme tokens or dark mode.
            darkMode: "media",
            theme: {},
            plugins: [],
        }),
    ]).process("@tailwind base;\n@tailwind utilities;\n", {
        from: undefined,
    });

    const css = result.css;

    const banner = [
        "// AUTO-GENERATED by scripts/build-pdf-css.mjs — do not edit by hand.",
        "// Regenerate with `npm run build:pdf-css`.",
        "",
        "export const PDF_TAILWIND_CSS = String.raw`",
    ].join("\n");

    // String.raw still terminates on a backtick and interpolates on ${.
    const escaped = css.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

    await mkdir(dirname(outFile), { recursive: true });
    await writeFile(outFile, `${banner}${escaped}\`;\n`, "utf8");

    const kb = (Buffer.byteLength(css, "utf8") / 1024).toFixed(1);
    console.log(`[pdf-css] wrote ${outFile} (${kb} kB)`);
}

main().catch((error) => {
    console.error("[pdf-css] failed to build PDF stylesheet:", error);
    process.exit(1);
});
